version: "3"

services:
  simphony:
    image: "registry.gitlab.cc-asp.fraunhofer.de/reaxpro/simphony-catalytic:${BUILD_VERSION:-latest}"
    build:
      context: "."
      args:
        - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
        - GITLAB_ACCESS_TOKEN=$GITLAB_ACCESS_TOKEN
        - CATALYTIC_FOAM_REPO=$CATALYTIC_FOAM_REPO
        - EIGEN_REPO=$EIGEN_REPO
      target: "${DOCKER_BUILD_TARGET:-develop}"
    tty: True
    entrypoint: /bin/bash
    environment:
      GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
      REAXPRO_MINIO_ENDPOINT: minio:9000
      REAXPRO_MINIO_USER: ${REAXPRO_MINIO_USER}
      REAXPRO_MINIO_PASSWORD: ${REAXPRO_MINIO_PASSWORD}
    volumes:
      - ./:/app:rw
    networks:
      - reaxpro

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000
    environment:
      MINIO_ROOT_USER: ${REAXPRO_MINIO_USER}
      MINIO_ROOT_PASSWORD: ${REAXPRO_MINIO_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data
    networks:
      - reaxpro

volumes:
  minio-data:


networks:
  reaxpro:
