---
name: Release

on:
    push:
        tags:
            - v*
        branches:
            - release/*

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v3

            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: '3.9'

            - name: Install pypa/build
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  python -m pip install osp-core build

            - name: Build a binary wheel and a source tarball
              run: |
                  python -m build --sdist --wheel --outdir dist/

            - name: Upload distribution artifact
              uses: actions/upload-artifact@v3
              with:
                  name: release
                  path: dist/

    publish:

        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/download-artifact@v3
              name: Download distribution artifact
              with:
                  name: release
                  path: dist/

            - uses: softprops/action-gh-release@v0.1.14
              name: Create release
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  files: |
                      dist/*
                  generate_release_notes: true

            - name: Publish distribution on PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
